/**
 * AI Red Team Report Generator
 *
 * Formats batch-run results and risk scores into shareable
 * Markdown reports and JSON exports.
 */

import type { ProbeResult, ProbeCategory } from "./probe-library";
import type { OverallRiskScore, CategoryRiskScore } from "./risk-scorer";
import type { BatchRunSummary } from "./batch-runner";

export interface ReportInput {
	targetName: string;
	targetDescription?: string;
	batchSummary: BatchRunSummary;
	riskScore: OverallRiskScore;
	notes?: string[];
}

export interface GeneratedReport {
	markdown: string;
	json: string;
	filenameBase: string;
}

function categoryEmoji(severity: CategoryRiskScore["severity"]): string {
	switch (severity) {
		case "critical":
			return "🔴";
		case "high":
			return "🟠";
		case "medium":
			return "🟡";
		case "low":
			return "🟢";
	}
}

function _severityColor(severity: string): string {
	switch (severity) {
		case "critical":
			return "#d32f2f";
		case "high":
			return "#f57c00";
		case "medium":
			return "#fbc02d";
		case "low":
			return "#388e3c";
		default:
			return "#757575";
	}
}

export function generateReport(input: ReportInput): GeneratedReport {
	const { targetName, targetDescription, batchSummary, riskScore, notes } = input;
	const timestamp = new Date().toISOString();
	const filenameBase = `ai-red-team-${targetName.toLowerCase().replace(/[^a-z0-9]+/g, "-")}-${timestamp.slice(0, 10)}`;
	const passedCount = riskScore.passedProbes.length;
	const failedCount = riskScore.failedProbes.length;
	const errorCount = riskScore.errorProbes.length;

	// Markdown report
	const mdLines: string[] = [
		"# AI Red Team Assessment Report",
		"",
		`> **Target:** ${targetName}`,
		`> **Generated:** ${timestamp}`,
		`> **Tool:** ORPHEUS AI Red Teaming`,
		"",
	];

	if (targetDescription) {
		mdLines.push("## Target Description", "", targetDescription, "");
	}

	mdLines.push(
		"## Executive Summary",
		"",
		`${riskScore.summary}`,
		"",
		"### Overall Risk Score",
		"",
		"| Metric | Value |",
		"| --- | --- |",
		`| Overall Score | ${riskScore.overallScore} / 100 |`,
		`| Overall Severity | ${riskScore.overallSeverity.toUpperCase()} |`,
		`| Total Probes | ${batchSummary.progress.total} |`,
		`| Passed | ${passedCount} |`,
		`| Failed | ${failedCount} |`,
		`| Errors | ${errorCount} |`,
		`| Skipped | ${batchSummary.progress.skipped} |`,
		`| Duration | ${batchSummary.durationMs}ms |`,
		`| Cancelled | ${batchSummary.cancelled ? "Yes" : "No"} |`,
		"",
		"## Category Breakdown",
		"",
		"| Category | Severity | Passed | Failed | Errors | Total | Avg Score | Max Score | Weighted |",
		"| --- | --- | --- | --- | --- | --- | --- | --- | --- |"
	);

	for (const cat of riskScore.categoryScores) {
		mdLines.push(
			`| ${cat.category} | ${categoryEmoji(cat.severity)} ${cat.severity.toUpperCase()} | ${cat.passed} | ${cat.failed} | ${cat.errors} | ${cat.total} | ${cat.avgScore} | ${cat.maxScore} | ${cat.weightedScore} |`
		);
	}

	mdLines.push("", "## Detailed Results", "");

	const byCategory = new Map<ProbeCategory, ProbeResult[]>();
	for (const r of batchSummary.results) {
		const list = byCategory.get(r.category) ?? [];
		list.push(r);
		byCategory.set(r.category, list);
	}

	for (const [category, results] of Array.from(byCategory.entries())) {
		mdLines.push(`### ${category}`, "");
		for (const r of results) {
			mdLines.push(
				`#### ${r.probeId} (${r.status.toUpperCase()})`,
				"",
				`- **Severity:** ${r.severity}`,
				`- **Score:** ${r.score}`,
				`- **Latency:** ${r.latencyMs}ms`,
				`- **Indicators:** ${r.matchedIndicators.join(", ") || "none"}`,
				"",
				"```text",
				"Input:",
				`${r.input}`,
				"",
				"Output:",
				`${r.output || "(no output)"}`,
				"```",
				""
			);
		}
	}

	if (notes && notes.length > 0) {
		mdLines.push("## Notes", "");
		for (const note of notes) {
			mdLines.push(`- ${note}`);
		}
		mdLines.push("");
	}

	mdLines.push(
		"---",
		"",
		"*Report generated by ORPHEUS AI Red Teaming. Results are heuristic-based and should be validated by human reviewers.*"
	);

	// JSON report
	const jsonPayload = {
		meta: {
			targetName,
			targetDescription,
			generatedAt: timestamp,
			tool: "ORPHEUS AI Red Teaming",
			version: "1.0.0",
		},
		summary: {
			overallScore: riskScore.overallScore,
			overallSeverity: riskScore.overallSeverity,
			failedProbes: riskScore.failedProbes,
			passedProbes: riskScore.passedProbes,
			errorProbes: riskScore.errorProbes,
			progress: batchSummary.progress,
			durationMs: batchSummary.durationMs,
			cancelled: batchSummary.cancelled,
		},
		categoryScores: riskScore.categoryScores,
		results: batchSummary.results.map((r) => ({
			probeId: r.probeId,
			status: r.status,
			category: r.category,
			severity: r.severity,
			score: r.score,
			latencyMs: r.latencyMs,
			matchedIndicators: r.matchedIndicators,
			input: r.input,
			output: r.output,
			runAt: r.runAt,
			error: r.error,
		})),
		notes: notes ?? [],
	};

	return {
		markdown: mdLines.join("\n"),
		json: JSON.stringify(jsonPayload, null, 2),
		filenameBase,
	};
}
