import { promises as fs } from "node:fs";
import path from "node:path";
import { getAppConfigDir } from "../utils/preferences";
import { buildRemediationSlaMarkdown, summarizeRemediationSla } from "./remediation-sla";
import {
	type SecurityControlMapping,
	buildSecurityControlMappings,
	summarizeControlMappings,
} from "./security-control-mapping";
import type {
	ClientEngagement,
	EngagementSyncResult,
	RemediationLedgerIssue,
} from "./security-engagements";
import {
	type SecurityEvidenceManifest,
	buildSecurityEvidenceManifest,
} from "./security-evidence-manifest";
import { updateSecurityPackIndex } from "./security-pack-index";
import { buildSecurityPortalHtml } from "./security-portal";
import type { WindowsAssessmentDiff, WindowsAssessmentRecord } from "./windows-assessment-history";
import type { AssessmentFinding } from "./windows-assessment-parser";
import type { RemediationStep } from "./windows-remediation";
import {
	buildWindowsSecurityScheduledTaskInventoryCommand,
	listWindowsSecurityScheduledTaskTemplates,
} from "./windows-scheduled-tasks";
import type { WindowsSecurityPlaybookId } from "./windows-security-playbooks";
import type { WindowsSecurityReport } from "./windows-security-report";

export interface SecurityEvidencePackInput {
	clientName: string;
	playbookId: WindowsSecurityPlaybookId;
	command: string;
	commandOutput: string;
	findings: AssessmentFinding[];
	remediationPlan: RemediationStep[];
	report: WindowsSecurityReport;
	history: { record: WindowsAssessmentRecord; diff: WindowsAssessmentDiff };
	engagement?: ClientEngagement;
	ledger?: RemediationLedgerIssue[];
	ledgerSync?: Pick<
		EngagementSyncResult,
		"openedIssueIds" | "verifiedIssueIds" | "unchangedIssueIds"
	>;
	generatedAt?: Date;
}

export interface SecurityEvidencePackExport {
	path: string;
	manifestPath: string;
	portalPath: string;
	indexPath: string;
	indexJsonPath: string;
	bytesWritten: number;
	markdown: string;
	manifest: SecurityEvidenceManifest;
	portalHtml: string;
	indexHtml: string;
}

function slugify(value: string): string {
	const slug = value
		.trim()
		.toLowerCase()
		.replace(/[^a-z0-9]+/g, "-")
		.replace(/^-+|-+$/g, "");
	return slug || "client";
}

function timestampForFilename(date: Date): string {
	return date
		.toISOString()
		.replace(/[-:]/g, "")
		.replace(/\.\d{3}Z$/, "Z");
}

function findingTitleMap(findings: AssessmentFinding[]): Map<string, string> {
	return new Map(findings.map((finding) => [finding.id, finding.title]));
}

function formatDiff(diff: WindowsAssessmentDiff, currentFindings: AssessmentFinding[]): string {
	const titles = findingTitleMap(currentFindings);
	const added = diff.addedFindingIds.map((id) => `- Added: ${titles.get(id) ?? id}`).join("\n");
	const resolved = diff.resolvedFindingIds.map((id) => `- Resolved: ${id}`).join("\n");
	const unchanged = diff.unchangedFindingIds
		.map((id) => `- Unchanged: ${titles.get(id) ?? id}`)
		.join("\n");

	return [
		`Previous assessment: ${diff.previousId ?? "none"}`,
		`Current assessment: ${diff.currentId}`,
		added || "- Added: none",
		resolved || "- Resolved: none",
		unchanged || "- Unchanged: none",
	].join("\n");
}

function formatFindings(findings: AssessmentFinding[]): string {
	if (findings.length === 0) return "- No findings were produced.";
	return findings
		.map(
			(finding) =>
				`### ${finding.severity.toUpperCase()} - ${finding.title}\n\n` +
				`Finding ID: ${finding.id}\n\n` +
				`Evidence:\n\n\`\`\`text\n${finding.evidence.slice(0, 1500).trim()}\n\`\`\`\n\n` +
				`Risk: ${finding.risk}\n\n` +
				`Remediation: ${finding.remediation}\n\n` +
				`Confidence: ${finding.confidence}`
		)
		.join("\n\n");
}

function formatRemediation(remediationPlan: RemediationStep[]): string {
	if (remediationPlan.length === 0) {
		return "- No approval-required remediation steps were generated by the parser.";
	}
	return remediationPlan
		.map(
			(step, index) =>
				`${index + 1}. ${step.title}\n` +
				`   - Finding ID: ${step.findingId}\n` +
				`   - Risk: ${step.riskLevel}\n` +
				`   - Proposed action: ${step.proposedAction}\n` +
				`   - Approval status: not started\n` +
				`   - Rollback: ${step.rollback}`
		)
		.join("\n");
}

function formatEngagement(input: SecurityEvidencePackInput): string {
	if (!input.engagement) return "- Client registry entry was not attached to this pack.";
	return [
		`- Client ID: ${input.engagement.id}`,
		`- Status: ${input.engagement.status}`,
		`- Risk tier: ${input.engagement.riskTier}`,
		`- Last assessment: ${input.engagement.lastAssessmentAt ?? "not recorded"}`,
		`- Contacts: ${input.engagement.contacts.length > 0 ? input.engagement.contacts.join(", ") : "not recorded"}`,
		`- Environment notes: ${
			input.engagement.environmentNotes.length > 0
				? input.engagement.environmentNotes.join("; ")
				: "not recorded"
		}`,
	].join("\n");
}

function formatLedger(input: SecurityEvidencePackInput): string {
	const sync = input.ledgerSync;
	const ledger = input.ledger ?? [];
	const summary = sync
		? [
				`- Newly opened: ${sync.openedIssueIds.length}`,
				`- Verified resolved: ${sync.verifiedIssueIds.length}`,
				`- Still present: ${sync.unchangedIssueIds.length}`,
			].join("\n")
		: "- Ledger sync summary was not attached.";

	const issues =
		ledger.length > 0
			? ledger
					.map(
						(issue) =>
							`- ${issue.id}: ${issue.status} / ${issue.severity} - ${issue.title} (last seen ${issue.lastSeenAssessmentId})`
					)
					.join("\n")
			: "- No ledger issues are currently tracked for this client.";

	return [summary, "", "Tracked issues:", issues].join("\n");
}

function formatControlMappings(mappings: SecurityControlMapping[]): string {
	const summary = summarizeControlMappings(mappings);
	const lines = mappings.map(
		(mapping) =>
			`- ${mapping.framework} ${mapping.id}: ${mapping.status} - ${mapping.title}. Gaps: ${
				mapping.gaps.length > 0 ? mapping.gaps.join("; ") : "none"
			}`
	);

	return [
		`Summary: ${summary.confirmed} confirmed, ${summary.partial} partial, ${summary.unknown} unknown, ${summary.failed} failed.`,
		"",
		...lines,
	].join("\n");
}

function formatScheduledTaskVerification(): string {
	const templates = listWindowsSecurityScheduledTaskTemplates()
		.map(
			(template) =>
				`- ${template.name}: ${template.description} Default: ${template.defaultTrigger}`
		)
		.join("\n");
	return [
		"Defensive task templates available:",
		templates,
		"",
		"Verification command:",
		"```powershell",
		buildWindowsSecurityScheduledTaskInventoryCommand(),
		"```",
	].join("\n");
}

export function buildSecurityEvidencePackMarkdown(input: SecurityEvidencePackInput): string {
	const generatedAt = input.generatedAt ?? new Date();
	const rawOutputPreview = input.commandOutput.trim().slice(0, 6000);
	const controlMappings = buildSecurityControlMappings(input.findings, input.report);

	return [
		`# Managed Security Evidence Pack`,
		"",
		`Client: ${input.clientName}`,
		`Prepared by: ORPHEUS`,
		`Generated at: ${generatedAt.toISOString()}`,
		`Assessment record: ${input.history.record.id}`,
		"",
		"## Client Engagement Registry",
		formatEngagement(input),
		"",
		"## Executive Security Snapshot",
		input.report.markdown,
		"",
		"## Before/After Delta",
		formatDiff(input.history.diff, input.findings),
		"",
		"## Technical Findings Appendix",
		formatFindings(input.findings),
		"",
		"## Remediation Tracker",
		formatRemediation(input.remediationPlan),
		"",
		"## Remediation Ledger",
		formatLedger(input),
		"",
		"## Remediation SLA",
		buildRemediationSlaMarkdown(input.ledger ?? [], generatedAt),
		"",
		"## Control Mapping",
		formatControlMappings(controlMappings),
		"",
		"## Scheduled Task Verification",
		formatScheduledTaskVerification(),
		"",
		"## Evidence Bundle Manifest",
		`- Playbook: ${input.playbookId}`,
		`- Command count: 1 bundled read-only PowerShell command`,
		`- Findings parsed: ${input.findings.length}`,
		`- Remediation steps generated: ${input.remediationPlan.length}`,
		`- Report risk: ${input.report.risk}`,
		`- Report score: ${input.report.score}/100`,
		`- Control mappings: ${controlMappings.length}`,
		"",
		"Assessment command used:",
		"```powershell",
		input.command,
		"```",
		"",
		"Raw output preview:",
		"```text",
		rawOutputPreview || "No command output was captured.",
		"```",
		"",
		"## Sharing Note",
		"This evidence pack may contain local security posture details. Review before sharing outside the client engagement.",
		"",
	].join("\n");
}

export async function exportSecurityEvidencePack(
	input: SecurityEvidencePackInput,
	options: { outputDir?: string } = {}
): Promise<SecurityEvidencePackExport> {
	const generatedAt = input.generatedAt ?? new Date();
	const outputDir =
		options.outputDir ??
		path.join(getAppConfigDir(), "engagements", slugify(input.clientName), "evidence-packs");
	const outputPath = path.join(
		outputDir,
		`${slugify(input.clientName)}-evidence-pack-${timestampForFilename(generatedAt)}.md`
	);
	const portalPath = path.join(
		outputDir,
		`${slugify(input.clientName)}-executive-portal-${timestampForFilename(generatedAt)}.html`
	);
	const manifestPath = path.join(
		outputDir,
		`${slugify(input.clientName)}-evidence-manifest-${timestampForFilename(generatedAt)}.json`
	);
	const markdown = buildSecurityEvidencePackMarkdown({ ...input, generatedAt });
	const normalizedInput = { ...input, generatedAt };
	const controlMappings = buildSecurityControlMappings(input.findings, input.report);
	const portalHtml = buildSecurityPortalHtml({
		input: normalizedInput,
		controlMappings,
		generatedAt,
	});
	const manifest = buildSecurityEvidenceManifest({
		input: normalizedInput,
		markdown,
		markdownPath: outputPath,
		portalHtml,
		portalPath,
		controlMappings,
		generatedAt,
	});

	await fs.mkdir(outputDir, { recursive: true });
	await fs.writeFile(outputPath, markdown, "utf8");
	await fs.writeFile(portalPath, portalHtml, "utf8");
	await fs.writeFile(manifestPath, JSON.stringify(manifest, null, 2), "utf8");
	const slaSummary = summarizeRemediationSla(input.ledger ?? [], generatedAt);
	const verifiedIssues = (input.ledger ?? []).filter((issue) => issue.status === "verified").length;
	const packIndex = await updateSecurityPackIndex({
		outputDir,
		entry: {
			generatedAt: generatedAt.toISOString(),
			clientName: input.clientName,
			reportPath: outputPath,
			portalPath,
			manifestPath,
			assessmentRecordId: input.history.record.id,
			score: input.report.score,
			risk: input.report.risk,
			findings: input.findings.length,
			openIssues: slaSummary.activeCount,
			overdueIssues: slaSummary.overdueCount,
			verifiedIssues,
		},
	});

	return {
		path: outputPath,
		manifestPath,
		portalPath,
		indexPath: packIndex.indexPath,
		indexJsonPath: packIndex.indexJsonPath,
		bytesWritten: Buffer.byteLength(markdown, "utf8"),
		markdown,
		manifest,
		portalHtml,
		indexHtml: packIndex.html,
	};
}
